package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/_SAEFeatureStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sae.idl
* Sunday, February 1, 2009 10:24:12 PM EST
*/


/**
   * Common interface for SAE interface modules. Actual interface
   * modules must extend this interface.
   */
public class _SAEFeatureStub extends org.omg.CORBA.portable.ObjectImpl implements net.juniper.smgt.sae.sae.SAEFeature
{

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:smgt.juniper.net/sae/SAEFeature:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _SAEFeatureStub
