package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/_ServiceActivationEngineStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sae.idl
* Sunday, February 1, 2009 10:24:12 PM EST
*/


/**
   * The interface to the interface module manager of SAE.
   */
public class _ServiceActivationEngineStub extends org.omg.CORBA.portable.ObjectImpl implements net.juniper.smgt.sae.sae.ServiceActivationEngine
{


  /**
     * Retrieve a reference to an installed interface module.
     *
     * @param[in] name The name of the requested interface module.
     *
     * @return A reference to the interface module.
     *
     * @throws FeatureNotInstalled if the requested interface module
     * is not installed.
     */
  public net.juniper.smgt.sae.sae.SAEFeature getFeature (String name) throws net.juniper.smgt.sae.sae.FeatureNotInstalled
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getFeature", true);
                $out.write_string (name);
                $in = _invoke ($out);
                net.juniper.smgt.sae.sae.SAEFeature $result = net.juniper.smgt.sae.sae.SAEFeatureHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/FeatureNotInstalled:1.0"))
                    throw net.juniper.smgt.sae.sae.FeatureNotInstalledHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getFeature (name        );
            } finally {
                _releaseReply ($in);
            }
  } // getFeature


  /**
     * Retrieve list of installed names of installed interface modules.
     *
     * @return list of interface module names.
     */
  public String[] getFeatureNames ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getFeatureNames", true);
                $in = _invoke ($out);
                String $result[] = net.juniper.smgt.sae.sae.StringSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getFeatureNames (        );
            } finally {
                _releaseReply ($in);
            }
  } // getFeatureNames

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:smgt.juniper.net/sae/ServiceActivationEngine:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ServiceActivationEngineStub
