package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ACTIVATE_ON_LOGIN.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public interface ACTIVATE_ON_LOGIN
{

  /// Constructor. Automatic service activation trigger.
  public static final String value = "ACTIVATE_ON_LOGIN";
}
