package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/Action.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class Action implements org.omg.CORBA.portable.IDLEntity
{

  /// An action to be taken.
  public int operation = (int)0;

  /// The name of the service associated with the action.
  public String serviceName = null;

  public Action ()
  {
  } // ctor

  public Action (int _operation, String _serviceName)
  {
    operation = _operation;
    serviceName = _serviceName;
  } // ctor

} // class Action
