package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ActionSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * List of actions.
   * @deprecated Use ActionExtSeq.
   */
public final class ActionSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.Action value[] = null;

  public ActionSeqHolder ()
  {
  }

  public ActionSeqHolder (net.juniper.smgt.sae.sae.Action[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.ActionSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.ActionSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.ActionSeqHelper.type ();
  }

}
