package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/AddrInterfaceName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class AddrInterfaceName implements org.omg.CORBA.portable.IDLEntity
{
  public String ipAddress = null;

  ///< IP address in dotted decimal notation.
  public String intfName = null;

  ///< Name of the managed interface.
  public String vrName = null;

  public AddrInterfaceName ()
  {
  } // ctor

  public AddrInterfaceName (String _ipAddress, String _intfName, String _vrName)
  {
    ipAddress = _ipAddress;
    intfName = _intfName;
    vrName = _vrName;
  } // ctor

} // class AddrInterfaceName
