package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/DEFAULT_SESSION_NAME.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public interface DEFAULT_SESSION_NAME
{

  /// Constructor. Reserved session name.
  public static final String value = "default";
}
