package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/DhcpAttributesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/// Sequence of DHCP attributes
public final class DhcpAttributesHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.DhcpAttribute value[] = null;

  public DhcpAttributesHolder ()
  {
  }

  public DhcpAttributesHolder (net.juniper.smgt.sae.sae.DhcpAttribute[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.DhcpAttributesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.DhcpAttributesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.DhcpAttributesHelper.type ();
  }

}
