package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/DhcpAttribute.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class DhcpAttribute implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  ///<Attribute name. See net.juniper.smgt.sae.portal.DhcpProfile.
  public String value = null;

  public DhcpAttribute ()
  {
  } // ctor

  public DhcpAttribute (String _name, String _value)
  {
    name = _name;
    value = _value;
  } // ctor

} // class DhcpAttribute
