package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/FeatureNotInstalled.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sae.idl
* Sunday, February 1, 2009 10:24:12 PM EST
*/

public final class FeatureNotInstalled extends org.omg.CORBA.UserException
{
  public String message = null;

  public FeatureNotInstalled ()
  {
    super(FeatureNotInstalledHelper.id());
  } // ctor

  public FeatureNotInstalled (String _message)
  {
    super(FeatureNotInstalledHelper.id());
    message = _message;
  } // ctor


  public FeatureNotInstalled (String $reason, String _message)
  {
    super(FeatureNotInstalledHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class FeatureNotInstalled
