package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/OverloadException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class OverloadException extends org.omg.CORBA.UserException
{
  public String message = null;

  public OverloadException ()
  {
    super(OverloadExceptionHelper.id());
  } // ctor

  public OverloadException (String _message)
  {
    super(OverloadExceptionHelper.id());
    message = _message;
  } // ctor


  public OverloadException (String $reason, String _message)
  {
    super(OverloadExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class OverloadException
