package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ReadResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class ReadResult implements org.omg.CORBA.portable.IDLEntity
{
  public net.juniper.smgt.sae.sae.IdxPair result[] = null;

  ///<Index of the subscription-subscriber pair
  public net.juniper.smgt.sae.sae.Attr subscription[][] = null;

  ///<Subscription associated with a paired service
  public net.juniper.smgt.sae.sae.Attr service[][] = null;

  /// Requested subscriber attributes.
  public net.juniper.smgt.sae.sae.Attr attributes[] = null;

  public ReadResult ()
  {
  } // ctor

  public ReadResult (net.juniper.smgt.sae.sae.IdxPair[] _result, net.juniper.smgt.sae.sae.Attr[][] _subscription, net.juniper.smgt.sae.sae.Attr[][] _service, net.juniper.smgt.sae.sae.Attr[] _attributes)
  {
    result = _result;
    subscription = _subscription;
    service = _service;
    attributes = _attributes;
  } // ctor

} // class ReadResult
