package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/RegistrationSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


///Sequence of registration objects.
public final class RegistrationSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.Registration value[] = null;

  public RegistrationSeqHolder ()
  {
  }

  public RegistrationSeqHolder (net.juniper.smgt.sae.sae.Registration[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.RegistrationSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.RegistrationSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.RegistrationSeqHelper.type ();
  }

}
