package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/Registration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class Registration implements org.omg.CORBA.portable.IDLEntity
{
  public String macAddress = null;

  ///< MAC address of the device.
  public String loginName = null;

  ///< Subscriber's login name.
  public String userDn = null;

  ///< Distinguished name of the user profile.
  public String intfName = null;

  ///< Name of the managed interface to which the client device connects.
  public String vrName = null;

  ///< Name of the virtual router to which the client device connects.
  public String description = null;

  public Registration ()
  {
  } // ctor

  public Registration (String _macAddress, String _loginName, String _userDn, String _intfName, String _vrName, String _description)
  {
    macAddress = _macAddress;
    loginName = _loginName;
    userDn = _userDn;
    intfName = _intfName;
    vrName = _vrName;
    description = _description;
  } // ctor

} // class Registration
