package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/SAEFeatureOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sae.idl
* Sunday, February 1, 2009 10:24:12 PM EST
*/


/**
   * Common interface for SAE interface modules. Actual interface
   * modules must extend this interface.
   */
public interface SAEFeatureOperations 
{
} // interface SAEFeatureOperations
