package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/SAETHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/// Types of exceptions for ServiceAuthenticationException.
public final class SAETHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.SAET value = null;

  public SAETHolder ()
  {
  }

  public SAETHolder (net.juniper.smgt.sae.sae.SAET initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.SAETHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.SAETHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.SAETHelper.type ();
  }

}
