package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScheduleEntryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

abstract public class ScheduleEntryHelper
{
  private static String  _id = "IDL:smgt.juniper.net/sae/ScheduleEntry:1.0";

  public static void insert (org.omg.CORBA.Any a, net.juniper.smgt.sae.sae.ScheduleEntry that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static net.juniper.smgt.sae.sae.ScheduleEntry extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          _tcOf_members0 = net.juniper.smgt.sae.sae.ScheduledTimeHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "schedTime",
            _tcOf_members0,
            null);
          _tcOf_members0 = net.juniper.smgt.sae.sae.ActionExtHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (net.juniper.smgt.sae.sae.ActionExtSeqHelper.id (), "ActionExtSeq", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "actions",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (net.juniper.smgt.sae.sae.ScheduleEntryHelper.id (), "ScheduleEntry", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static net.juniper.smgt.sae.sae.ScheduleEntry read (org.omg.CORBA.portable.InputStream istream)
  {
    net.juniper.smgt.sae.sae.ScheduleEntry value = new net.juniper.smgt.sae.sae.ScheduleEntry ();
    value.id = istream.read_string ();
    value.schedTime = net.juniper.smgt.sae.sae.ScheduledTimeHelper.read (istream);
    value.actions = net.juniper.smgt.sae.sae.ActionExtSeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.juniper.smgt.sae.sae.ScheduleEntry value)
  {
    ostream.write_string (value.id);
    net.juniper.smgt.sae.sae.ScheduledTimeHelper.write (ostream, value.schedTime);
    net.juniper.smgt.sae.sae.ActionExtSeqHelper.write (ostream, value.actions);
  }

}
