package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScheduleEntrySeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


///Sequence of entries for a service schedule.
public final class ScheduleEntrySeqHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.ScheduleEntry value[] = null;

  public ScheduleEntrySeqHolder ()
  {
  }

  public ScheduleEntrySeqHolder (net.juniper.smgt.sae.sae.ScheduleEntry[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.ScheduleEntrySeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.ScheduleEntrySeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.ScheduleEntrySeqHelper.type ();
  }

}
