package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScriptExecutionError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saescript.idl
* Sunday, February 1, 2009 10:24:23 PM EST
*/

public final class ScriptExecutionError extends org.omg.CORBA.UserException
{
  public String message = null;

  public ScriptExecutionError ()
  {
    super(ScriptExecutionErrorHelper.id());
  } // ctor

  public ScriptExecutionError (String _message)
  {
    super(ScriptExecutionErrorHelper.id());
    message = _message;
  } // ctor


  public ScriptExecutionError (String $reason, String _message)
  {
    super(ScriptExecutionErrorHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ScriptExecutionError
