package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/ScriptExecutionErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saescript.idl
* Sunday, February 1, 2009 10:24:23 PM EST
*/

public final class ScriptExecutionErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.ScriptExecutionError value = null;

  public ScriptExecutionErrorHolder ()
  {
  }

  public ScriptExecutionErrorHolder (net.juniper.smgt.sae.sae.ScriptExecutionError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.ScriptExecutionErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.ScriptExecutionErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.ScriptExecutionErrorHelper.type ();
  }

}
