package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScriptSyntaxError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saescript.idl
* Sunday, February 1, 2009 10:24:23 PM EST
*/

public final class ScriptSyntaxError extends org.omg.CORBA.UserException
{
  public String message = null;

  public ScriptSyntaxError ()
  {
    super(ScriptSyntaxErrorHelper.id());
  } // ctor

  public ScriptSyntaxError (String _message)
  {
    super(ScriptSyntaxErrorHelper.id());
    message = _message;
  } // ctor


  public ScriptSyntaxError (String $reason, String _message)
  {
    super(ScriptSyntaxErrorHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ScriptSyntaxError
