package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ServiceActivationEngine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sae.idl
* Sunday, February 1, 2009 10:24:12 PM EST
*/


/**
   * The interface to the interface module manager of SAE.
   */
public interface ServiceActivationEngine extends ServiceActivationEngineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServiceActivationEngine
