package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ServiceActivationEngineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sae.idl
* Sunday, February 1, 2009 10:24:12 PM EST
*/


/**
   * The interface to the interface module manager of SAE.
   */
public interface ServiceActivationEngineOperations 
{

  /**
     * Retrieve a reference to an installed interface module.
     *
     * @param[in] name The name of the requested interface module.
     *
     * @return A reference to the interface module.
     *
     * @throws FeatureNotInstalled if the requested interface module
     * is not installed.
     */
  net.juniper.smgt.sae.sae.SAEFeature getFeature (String name) throws net.juniper.smgt.sae.sae.FeatureNotInstalled;

  /**
     * Retrieve list of installed names of installed interface modules.
     *
     * @return list of interface module names.
     */
  String[] getFeatureNames ();
} // interface ServiceActivationEngineOperations
