package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/ServiceAuthenticationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class ServiceAuthenticationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.ServiceAuthenticationException value = null;

  public ServiceAuthenticationExceptionHolder ()
  {
  }

  public ServiceAuthenticationExceptionHolder (net.juniper.smgt.sae.sae.ServiceAuthenticationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.ServiceAuthenticationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.ServiceAuthenticationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.ServiceAuthenticationExceptionHelper.type ();
  }

}
