package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/Subscriber.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * Interface that is used to manage an active subscriber session.
   * Lets you get information about the session, make service schedules
   * available, add and remove subscriptions, set the session timeout,
   * manage session login, and activate and deactivate services.
   *
   * \b NOTE: All methods raise an UnknownUserException if the subscriber
   * session is no longer active.
   */
public interface Subscriber extends SubscriberOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Subscriber
