package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/SubscriberIteratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * Interface that is used to iteratively retrieve subscriber objects that were
   * not transmitted from a single API call to the SAE.
   *
   * \b NOTE: If the SubscriberIterator is not used for an allotted time,
   * the garbage collector takes care of it.
   */
public final class SubscriberIteratorHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.SubscriberIterator value = null;

  public SubscriberIteratorHolder ()
  {
  }

  public SubscriberIteratorHolder (net.juniper.smgt.sae.sae.SubscriberIterator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.SubscriberIteratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.SubscriberIteratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.SubscriberIteratorHelper.type ();
  }

}
