package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/SubscriberHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * Interface that is used to manage an active subscriber session.
   * Lets you get information about the session, make service schedules
   * available, add and remove subscriptions, set the session timeout,
   * manage session login, and activate and deactivate services.
   *
   * \b NOTE: All methods raise an UnknownUserException if the subscriber
   * session is no longer active.
   */
public final class SubscriberHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.Subscriber value = null;

  public SubscriberHolder ()
  {
  }

  public SubscriberHolder (net.juniper.smgt.sae.sae.Subscriber initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.SubscriberHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.SubscriberHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.SubscriberHelper.type ();
  }

}
