package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/SubscriberIdHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

abstract public class SubscriberIdHelper
{
  private static String  _id = "IDL:smgt.juniper.net/sae/SubscriberId:1.0";

  public static void insert (org.omg.CORBA.Any a, net.juniper.smgt.sae.sae.SubscriberId that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static net.juniper.smgt.sae.sae.SubscriberId extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [9];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for address (case label SIT_ADDRESS)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_ADDRESS);
      _tcOf_members0 = net.juniper.smgt.sae.sae.TimedAddressHelper.type ();
      _members0[0] = new org.omg.CORBA.UnionMember (
        "address",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for dn (case label SIT_DN)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_DN);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[1] = new org.omg.CORBA.UnionMember (
        "dn",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for login_name (case label SIT_LOGIN_NAME)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_LOGIN_NAME);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[2] = new org.omg.CORBA.UnionMember (
        "login_name",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for if_name (case label SIT_IF_NAME)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_IF_NAME);
      _tcOf_members0 = net.juniper.smgt.sae.sae.InterfaceNameHelper.type ();
      _members0[3] = new org.omg.CORBA.UnionMember (
        "if_name",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for if_index (case label SIT_IF_INDEX)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_IF_INDEX);
      _tcOf_members0 = net.juniper.smgt.sae.sae.InterfaceIndexHelper.type ();
      _members0[4] = new org.omg.CORBA.UnionMember (
        "if_index",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for primary_user_name (case label SIT_PRIMARY_USER_NAME)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_PRIMARY_USER_NAME);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[5] = new org.omg.CORBA.UnionMember (
        "primary_user_name",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for addr_if_name (case label SIT_ADDR_IF_NAME)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_ADDR_IF_NAME);
      _tcOf_members0 = net.juniper.smgt.sae.sae.AddrInterfaceNameHelper.type ();
      _members0[6] = new org.omg.CORBA.UnionMember (
        "addr_if_name",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for tunnel_session (case label SIT_TUNNEL_SESSION)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_TUNNEL_SESSION);
      _tcOf_members0 = net.juniper.smgt.sae.sae.TunnelSessionHelper.type ();
      _members0[7] = new org.omg.CORBA.UnionMember (
        "tunnel_session",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for sessionId (case label SIT_SESSIONID)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.insert (_anyOf_members0, net.juniper.smgt.sae.sae.SubscriberIdType.SIT_SESSIONID);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[8] = new org.omg.CORBA.UnionMember (
        "sessionId",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (net.juniper.smgt.sae.sae.SubscriberIdHelper.id (), "SubscriberId", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static net.juniper.smgt.sae.sae.SubscriberId read (org.omg.CORBA.portable.InputStream istream)
  {
    net.juniper.smgt.sae.sae.SubscriberId value = new net.juniper.smgt.sae.sae.SubscriberId ();
    net.juniper.smgt.sae.sae.SubscriberIdType _dis0 = null;
    _dis0 = net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.read (istream);
    switch (_dis0.value ())
    {
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_ADDRESS:
        net.juniper.smgt.sae.sae.TimedAddress _address = null;
        _address = net.juniper.smgt.sae.sae.TimedAddressHelper.read (istream);
        value.address (_address);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_DN:
        String _dn = null;
        _dn = istream.read_string ();
        value.dn (_dn);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_LOGIN_NAME:
        String _login_name = null;
        _login_name = istream.read_string ();
        value.login_name (_login_name);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_IF_NAME:
        net.juniper.smgt.sae.sae.InterfaceName _if_name = null;
        _if_name = net.juniper.smgt.sae.sae.InterfaceNameHelper.read (istream);
        value.if_name (_if_name);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_IF_INDEX:
        net.juniper.smgt.sae.sae.InterfaceIndex _if_index = null;
        _if_index = net.juniper.smgt.sae.sae.InterfaceIndexHelper.read (istream);
        value.if_index (_if_index);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_PRIMARY_USER_NAME:
        String _primary_user_name = null;
        _primary_user_name = istream.read_string ();
        value.primary_user_name (_primary_user_name);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_ADDR_IF_NAME:
        net.juniper.smgt.sae.sae.AddrInterfaceName _addr_if_name = null;
        _addr_if_name = net.juniper.smgt.sae.sae.AddrInterfaceNameHelper.read (istream);
        value.addr_if_name (_addr_if_name);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_TUNNEL_SESSION:
        net.juniper.smgt.sae.sae.TunnelSession _tunnel_session = null;
        _tunnel_session = net.juniper.smgt.sae.sae.TunnelSessionHelper.read (istream);
        value.tunnel_session (_tunnel_session);
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_SESSIONID:
        String _sessionId = null;
        _sessionId = istream.read_string ();
        value.sessionId (_sessionId);
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.juniper.smgt.sae.sae.SubscriberId value)
  {
    net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_ADDRESS:
        net.juniper.smgt.sae.sae.TimedAddressHelper.write (ostream, value.address ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_DN:
        ostream.write_string (value.dn ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_LOGIN_NAME:
        ostream.write_string (value.login_name ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_IF_NAME:
        net.juniper.smgt.sae.sae.InterfaceNameHelper.write (ostream, value.if_name ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_IF_INDEX:
        net.juniper.smgt.sae.sae.InterfaceIndexHelper.write (ostream, value.if_index ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_PRIMARY_USER_NAME:
        ostream.write_string (value.primary_user_name ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_ADDR_IF_NAME:
        net.juniper.smgt.sae.sae.AddrInterfaceNameHelper.write (ostream, value.addr_if_name ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_TUNNEL_SESSION:
        net.juniper.smgt.sae.sae.TunnelSessionHelper.write (ostream, value.tunnel_session ());
        break;
      case net.juniper.smgt.sae.sae.SubscriberIdType._SIT_SESSIONID:
        ostream.write_string (value.sessionId ());
        break;
    }
  }

}
