package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/SubscriberSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * Sequence of subscriber objects.
   */
public final class SubscriberSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.Subscriber value[] = null;

  public SubscriberSeqHolder ()
  {
  }

  public SubscriberSeqHolder (net.juniper.smgt.sae.sae.Subscriber[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.SubscriberSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.SubscriberSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.SubscriberSeqHelper.type ();
  }

}
