package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/TimedAddress.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class TimedAddress implements org.omg.CORBA.portable.IDLEntity
{
  public String ipAddress = null;

  ///< IP address in dotted decimal notation.
  public long timestamp = (long)0;

  public TimedAddress ()
  {
  } // ctor

  public TimedAddress (String _ipAddress, long _timestamp)
  {
    ipAddress = _ipAddress;
    timestamp = _timestamp;
  } // ctor

} // class TimedAddress
