package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/TimeSpec.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class TimeSpec implements org.omg.CORBA.portable.IDLEntity
{

  // the attributes of time specification
  public String year = null;

  ///<Four digits that indicate the year.
  public String month = null;

  ///<Month of the year.
  public String dayOfMonth = null;

  ///<Day of the month.
  public String dayOfWeek = null;

  ///<Day of the week.
  public String hour = null;

  ///<Hour.
  public String minute = null;

  ///<Minute.
  public String extension = null;

  public TimeSpec ()
  {
  } // ctor

  public TimeSpec (String _year, String _month, String _dayOfMonth, String _dayOfWeek, String _hour, String _minute, String _extension)
  {
    year = _year;
    month = _month;
    dayOfMonth = _dayOfMonth;
    dayOfWeek = _dayOfWeek;
    hour = _hour;
    minute = _minute;
    extension = _extension;
  } // ctor

} // class TimeSpec
