package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/UnknownUserException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class UnknownUserException extends org.omg.CORBA.UserException
{
  public String userId = null;
  public String message = null;

  public UnknownUserException ()
  {
    super(UnknownUserExceptionHelper.id());
  } // ctor

  public UnknownUserException (String _userId, String _message)
  {
    super(UnknownUserExceptionHelper.id());
    userId = _userId;
    message = _message;
  } // ctor


  public UnknownUserException (String $reason, String _userId, String _message)
  {
    super(UnknownUserExceptionHelper.id() + "  " + $reason);
    userId = _userId;
    message = _message;
  } // ctor

} // class UnknownUserException
