package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/UnknownServiceSessionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class UnknownServiceSessionException extends org.omg.CORBA.UserException
{
  public String serviceName = null;
  public String sessionName = null;
  public String message = null;

  public UnknownServiceSessionException ()
  {
    super(UnknownServiceSessionExceptionHelper.id());
  } // ctor

  public UnknownServiceSessionException (String _serviceName, String _sessionName, String _message)
  {
    super(UnknownServiceSessionExceptionHelper.id());
    serviceName = _serviceName;
    sessionName = _sessionName;
    message = _message;
  } // ctor


  public UnknownServiceSessionException (String $reason, String _serviceName, String _sessionName, String _message)
  {
    super(UnknownServiceSessionExceptionHelper.id() + "  " + $reason);
    serviceName = _serviceName;
    sessionName = _sessionName;
    message = _message;
  } // ctor

} // class UnknownServiceSessionException
