package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/UnsupportedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class UnsupportedException extends org.omg.CORBA.UserException
{
  public String message = null;

  public UnsupportedException ()
  {
    super(UnsupportedExceptionHelper.id());
  } // ctor

  public UnsupportedException (String _message)
  {
    super(UnsupportedExceptionHelper.id());
    message = _message;
  } // ctor


  public UnsupportedException (String $reason, String _message)
  {
    super(UnsupportedExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class UnsupportedException
