package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/_SAEAccessStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * Interface to access the SAE core API.
   *
   * Descendant of sae.SAEFeature. 
   * Accessible through the ServiceActivationEngine interface
   * SAEFeature.getFeature.
   */
public class _SAEAccessStub extends org.omg.CORBA.portable.ObjectImpl implements net.juniper.smgt.sae.sae.SAEAccess
{


  /**
     * The getSubscriber() method retrieves a single subscriber object
     * by matching the specified attributes.
     *
     * @param[in] sid ID of the subscriber session.
     *
     * @return Single subscriber object.
     *
     * @throws UnknownUserException Raised if the subscriber is not
     * logged in to a subscriber session.
     *
     * @throws NonUniqueUserException Raised if there is more than one
     * active subscriber session for the specified subscriber ID.
     */
  public net.juniper.smgt.sae.sae.Subscriber getSubscriber (net.juniper.smgt.sae.sae.SubscriberId sid) throws net.juniper.smgt.sae.sae.UnknownUserException, net.juniper.smgt.sae.sae.NonUniqueUserException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSubscriber", true);
                net.juniper.smgt.sae.sae.SubscriberIdHelper.write ($out, sid);
                $in = _invoke ($out);
                net.juniper.smgt.sae.sae.Subscriber $result = net.juniper.smgt.sae.sae.SubscriberHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/UnknownUserException:1.0"))
                    throw net.juniper.smgt.sae.sae.UnknownUserExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/NonUniqueUserException:1.0"))
                    throw net.juniper.smgt.sae.sae.NonUniqueUserExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getSubscriber (sid        );
            } finally {
                _releaseReply ($in);
            }
  } // getSubscriber


  /**
     * The getSubscriberSet() method retrieves 0 or more subscriber
     * objects by using the subscriber ID.
     * 
     * The method takes the  same arguments as the getSubscriber() method, plus the
     * number of objects that the method should  return. If no subscriber is found,
     * the returned sequence can be empty.
     *
     * @param[in] sid ID of the subscriber session.
     *
     * @param[in] how_many Maximum number of session objects returned.
     *
     * @param[out] iter Iterator to retrieve the remaining sessions, if more
     * session than the specified number are returned. If the total number of sessions
     * is less than or equal to how_many, no iter is returned.
     *
     * @param[out] total Number of selected subscriber sessions.
     *
     * @return List of subscriber sessions.
     *
     */
  public net.juniper.smgt.sae.sae.Subscriber[] getSubscriberSet (net.juniper.smgt.sae.sae.SubscriberId sid, int how_many, net.juniper.smgt.sae.sae.SubscriberIteratorHolder iter, org.omg.CORBA.IntHolder total)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSubscriberSet", true);
                net.juniper.smgt.sae.sae.SubscriberIdHelper.write ($out, sid);
                $out.write_ulong (how_many);
                $in = _invoke ($out);
                net.juniper.smgt.sae.sae.Subscriber $result[] = net.juniper.smgt.sae.sae.SubscriberSeqHelper.read ($in);
                iter.value = net.juniper.smgt.sae.sae.SubscriberIteratorHelper.read ($in);
                total.value = $in.read_ulong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getSubscriberSet (sid, how_many, iter, total        );
            } finally {
                _releaseReply ($in);
            }
  } // getSubscriberSet


  /**
     * The findSubscriber() method identifies one or more subscribers by using
     * an LDAP filter. It returns the same items as  getSubscriberSet().
     * 
     * Although similar to the getSubscriberSet()
     * method,  it uses an LDAP filter rather than a subscriber ID and takes
     * as an argument the number of  objects that the method should return. 
     *
     * \b NOTE: Use this method only when necessary, because it searches
     * all active subscriber
     * sessions and takes a  significant amount of time to complete.
     *
     * @param[in] filter Simplified LDAP search filter that can access
     * attributes of the subscriber session. For more information about
     * simplified LDAP filters, see the documentation for the Select() method.
     *
     * @param[in] how_many Maximum number of session objects returned.
     *
     * @param[out] iter Iterator to retrieve the remaining
     * sessions, if more sessions than the specified number are returned. If the
     * total number of sessions is less than or equal to how_many, no iter is
     * returned.
     *
     * @param[out] total Number of specified subscriber sessions.
     *
     * @return List of subscriber sessions.
     *
     * @throws SAEException Raised if the filter cannot be parsed.
     */
  public net.juniper.smgt.sae.sae.Subscriber[] findSubscriber (String filter, int how_many, net.juniper.smgt.sae.sae.SubscriberIteratorHolder iter, org.omg.CORBA.IntHolder total) throws net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("findSubscriber", true);
                $out.write_string (filter);
                $out.write_ulong (how_many);
                $in = _invoke ($out);
                net.juniper.smgt.sae.sae.Subscriber $result[] = net.juniper.smgt.sae.sae.SubscriberSeqHelper.read ($in);
                iter.value = net.juniper.smgt.sae.sae.SubscriberIteratorHelper.read ($in);
                total.value = $in.read_ulong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return findSubscriber (filter, how_many, iter, total        );
            } finally {
                _releaseReply ($in);
            }
  } // findSubscriber


  /**
     * The getSubscriberFilter() method retrieves references to all subscriber sessions
     * that match a specified subscriber ID and the search-filter criteria.
     * 
     * The method first selects the objects that match the subscriber ID,
     * and then filters these objects to obtain the result.
     *
     * The getSubscriberFilter() method  is a combination of the getSubscriberSet()
     * and findSubscriber() methods. The method returns the same items as
     * getSubscriberSet().
     *
     * @param[in] sid ID of the subscriber sessions.
     *
     * @param[in] filter Simplified LDAP search filter that can access
     * attributes of the subscriber session. For more information about
     * simplified LDAP filters, see the documentation for the Select() method.
     * 
     * @param[in] how_many Maximum number of session objects returned.
     *
     * @param[in] iter Iterator to retrieve the remaining
     * sessions if more sessions than the specified number 
     * are returned. If the total number of sessions is less than or
     * equal how_many, no iter is returned.
     *
     * @param[in] total Number of selected subscriber sessions.
     *
     * @return List of subscriber sessions.
     *
     * @throws SAEException Raised if the filter cannot be parsed.
     */
  public net.juniper.smgt.sae.sae.Subscriber[] getSubscriberFilter (net.juniper.smgt.sae.sae.SubscriberId sid, String filter, int how_many, net.juniper.smgt.sae.sae.SubscriberIteratorHolder iter, org.omg.CORBA.IntHolder total) throws net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSubscriberFilter", true);
                net.juniper.smgt.sae.sae.SubscriberIdHelper.write ($out, sid);
                $out.write_string (filter);
                $out.write_ulong (how_many);
                $in = _invoke ($out);
                net.juniper.smgt.sae.sae.Subscriber $result[] = net.juniper.smgt.sae.sae.SubscriberSeqHelper.read ($in);
                iter.value = net.juniper.smgt.sae.sae.SubscriberIteratorHelper.read ($in);
                total.value = $in.read_ulong ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getSubscriberFilter (sid, filter, how_many, iter, total        );
            } finally {
                _releaseReply ($in);
            }
  } // getSubscriberFilter


  /**
     * The registerLogin() method creates login registration objects
     * in the directory for subscribers who use DHCP. 
     *
     * The SAE authenticates the specified loginName and password, and loads
     * the associated user profile. The name of this profile is stored in the
     * directory with the MAC address as the key. The next time the client device
     * connects to the router, the SAE loads the registered user profile.
     * Another authentication is not required.
     *
     * The creation of a subscriber session when the client device is activated
     * takes effect the next time that the client device requests
     * an IP address. 
     *
     * @param[in] macAddress		MAC address of the client device.
     *
     * @param[in] loginDescription	Description of the subscriber session.
     *     
     * @param[in] loginName		Subscriber's login name.
     *
     * @param[in] password		Subscriber's password associated with the login name.
     * 
     * @param[in] vrName		Name of the virtual router that manages
     *  the subscriber associated with the client device.
     *
     * @param[in] interfaceName	Name of the managed interface
     * that handles the subscriber associated with the client device.       
     *
     * @throws LoginException	Raised if a subscriber login to a subscriber session fails.
     *
     * @throws SAEException	Raised if there is an unspecified error condition
     * within the SAE.
     */
  public void registerLogin (String macAddress, String loginDescription, String loginName, String password, String vrName, String interfaceName) throws net.juniper.smgt.sae.sae.LoginException, net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerLogin", true);
                $out.write_string (macAddress);
                $out.write_wstring (loginDescription);
                $out.write_string (loginName);
                $out.write_string (password);
                $out.write_string (vrName);
                $out.write_string (interfaceName);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/LoginException:1.0"))
                    throw net.juniper.smgt.sae.sae.LoginExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerLogin (macAddress, loginDescription, loginName, password, vrName, interfaceName        );
            } finally {
                _releaseReply ($in);
            }
  } // registerLogin


  /**
     * The registerLoginCredentials() method passes the MAC address of the client
     * device, the subscriber's login name, and the associated password to the 
     * SAE to identify the client device that is connecting to the network
     * using DHCP.
     * 
     * The SAE stores the specified loginName and password in the directory
     * with the MAC address as the key. The next time that the client device
     * connects to the router, the SAE uses the loginName and password
     * to log in the subscriber and authenticate a user session.
     *
     * The creation of a subscriber session when the client device is activated
     * takes effect the next time that the client device requests an
     * IP address. 
     *
     * @param[in] macAddress			MAC address of the client device.
     * 
     * @param[in] loginDescription		Description of the subscriber session.
     * 
     * @param[in] loginName			Subscriber's login name.
     * 
     * @param[in] password			Subscriber's password associated with
     * the login name.
     * 
     * @param[in] vrName			Name of the virtual router that manages
     * the subscriber associated with the client device. 
     *
     * @param[in] interfaceName	Name of the managed interface
     * that handles the subscriber associated with the client device.       
     *
     * @throws LoginException		Raised if a subscriber login to a subscriber session.
     * fails
     *
     * @throws SAEException		Raised if there is an unspecified error.
     * condition within the SAE
     */
  public void registerLoginCredentials (String macAddress, String loginDescription, String loginName, String password, String vrName, String interfaceName) throws net.juniper.smgt.sae.sae.LoginException, net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerLoginCredentials", true);
                $out.write_string (macAddress);
                $out.write_wstring (loginDescription);
                $out.write_string (loginName);
                $out.write_string (password);
                $out.write_string (vrName);
                $out.write_string (interfaceName);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/LoginException:1.0"))
                    throw net.juniper.smgt.sae.sae.LoginExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerLoginCredentials (macAddress, loginDescription, loginName, password, vrName, interfaceName        );
            } finally {
                _releaseReply ($in);
            }
  } // registerLoginCredentials


  /**
     * The registerNextLogin() method creates temporary login registration
     * objects in memory for subscribers who use DHCP.
     * The SDX software removes the temporary object either the next time
     *  the subscriber logs
     * in or after a certain time elapses, depending on which event occurs first.
     *
     * The method passes credentials for subscribers to the
     * SAE. These credentials are used to obtain an authenticated IP address only
     * for the next subscriber session. 
     *
     * @param[in] macAddress		MAC address of the client device.
     * 
     * @param[in] loginDescription  Description of the subscriber session.
     * 
     * @param[in] loginName		Subscriber's login name.
     *
     * @param[in] password		Subscriber's password associated with the login name.
     *  
     * @param[in] vrName		Name of the virtual router that manages
     * the subscriber associated with the client device.
     *
     * @param[in] interfaceName	Managed interface
     * that handles the subscriber associated with the client device.       
     *
     * @throws LoginException  Raised if a subscriber login to a subscriber session fails.
     *
     * @throws SAEException      Raised if there is an unspecified error condition
     * within the SAE.
     */
  public void registerNextLogin (String macAddress, String loginDescription, String loginName, String password, String vrName, String interfaceName) throws net.juniper.smgt.sae.sae.LoginException, net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerNextLogin", true);
                $out.write_string (macAddress);
                $out.write_wstring (loginDescription);
                $out.write_string (loginName);
                $out.write_string (password);
                $out.write_string (vrName);
                $out.write_string (interfaceName);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/LoginException:1.0"))
                    throw net.juniper.smgt.sae.sae.LoginExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerNextLogin (macAddress, loginDescription, loginName, password, vrName, interfaceName        );
            } finally {
                _releaseReply ($in);
            }
  } // registerNextLogin


  /**
     * The unregisterLogin() method deletes registration objects
     * from the directory.
     *
     * The method passes to the SAE the MAC address of the
     * client device and the subscriber's login name and password.
     * The SAE removes registration information from the directory for
     * subscribers who connect using DHCP and have
     * registered their client device.
     *
     * @param[in] macAddress	MAC address of the client device.
     * 
     * @param[in] loginName	Subscriber's login name.
     *
     * @param[in] password	Subscriber's password associated with the login name. 
     *
     * @throws LoginException Raised if a subscriber login to a subscriber session fails.	
     *
     * @throws SAEException  	Raised if there is an unspecified error condition
     * within the SAE.
     */
  public void unregisterLogin (String macAddress, String loginName, String password) throws net.juniper.smgt.sae.sae.LoginException, net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("unregisterLogin", true);
                $out.write_string (macAddress);
                $out.write_string (loginName);
                $out.write_string (password);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/LoginException:1.0"))
                    throw net.juniper.smgt.sae.sae.LoginExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                unregisterLogin (macAddress, loginName, password        );
            } finally {
                _releaseReply ($in);
            }
  } // unregisterLogin


  /**
     * The registerEquipment() method creates an entry in the directory for
     * permanent IP addresses assigned to DHCP connections. The information
     * stored in the directory is
     * used to obtain an authenticated IP address.
     * 
     * \n \b NOTE: The registerEquipment() method can be used
     * only with JUNOSe routers. 
     *
     * @param[in] macAddress			MAC address of the client device.
     *
     * @param[in] equipmentDescription	Description of the client device.
     *
     * @param[in] loginName			Subscriber's login name.
     *  
     * @param[in] password			Subscriber's password associated with
     * the login name.
     * 
     * @param[in] vrName			Name of the virtual router that manages
     * the subscriber associated with the client device.
     *
     * @param[in] interfaceName		Name of the managed interface
     * that handles the subscriber associated with the client device.       
     *
     * @throws SAEException	Raised if there is an unspecified error condition
     * within the SAE.
     */
  public void registerEquipment (String macAddress, String equipmentDescription, String loginName, String password, String vrName, String interfaceName) throws net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerEquipment", true);
                $out.write_string (macAddress);
                $out.write_wstring (equipmentDescription);
                $out.write_string (loginName);
                $out.write_string (password);
                $out.write_string (vrName);
                $out.write_string (interfaceName);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerEquipment (macAddress, equipmentDescription, loginName, password, vrName, interfaceName        );
            } finally {
                _releaseReply ($in);
            }
  } // registerEquipment


  /**
     * The registerEquipmentAttr() method creates an entry in the directory for
     * permanent IP addresses assigned to DHCP connections. The
     * information stored in the directory is
     * used to obtain an authenticated IP address. The registerEquipmentAttr() method 
     * uses DHCP attributes for device registration in addition to the attributes
     * used by the registerEquipment() method.
     *
     * The registerEquipmentAttr() method can be used only with JUNOSe routers.
     *
     * @param[in] macAddress			MAC address of the client device.
     * 
     * @param[in] equipmentDescription	Description of the client device.
     *
     * @param[in] loginName			Subscriber's login name.
     *  
     * @param[in] password			Subscriber's password associated with
     * the login name. 
     *
     * @param[in] vrName			Name of the virtual router that manages
     * the subscriber associated with the client device.
     *
     * @param[in] interfaceName	Name of the managed interface
     * that handles the subscriber associated with the client device. 
     *      
     * @param[in] attr              Value of string name for Attr.			
     *
     * @throws SAEException		Raised if there is an unspecified error
     * condition within the SAE.
     */
  public void registerEquipmentAttr (String macAddress, String equipmentDescription, String loginName, String password, String vrName, String interfaceName, net.juniper.smgt.sae.sae.DhcpAttribute[] attr) throws net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerEquipmentAttr", true);
                $out.write_string (macAddress);
                $out.write_wstring (equipmentDescription);
                $out.write_string (loginName);
                $out.write_string (password);
                $out.write_string (vrName);
                $out.write_string (interfaceName);
                net.juniper.smgt.sae.sae.DhcpAttributesHelper.write ($out, attr);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerEquipmentAttr (macAddress, equipmentDescription, loginName, password, vrName, interfaceName, attr        );
            } finally {
                _releaseReply ($in);
            }
  } // registerEquipmentAttr


  /**
     * The unregisterEquipment() method removes entries from the directory
     * for permanent IP addresses that are assigned to DHCP connections. 
     * The method disables client device registration
     * for subscribers who have registered their client device and who use a DHCP 
     * connection.
     *
     * The unregisterEquipment() method can be used only with JUNIOSe routers.
     *
     * @param[in] macAddress		MAC address of a client device.
     *
     * @param[in] loginName		Subscriber's login name.
     *  
     * @param[in] password		Subscriber's password associated with the login name. 
     *
     * @throws SAEException         Raised if there is an unspecified error
     * condition within the SAE.
     */
  public void unregisterEquipment (String macAddress, String loginName, String password) throws net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("unregisterEquipment", true);
                $out.write_string (macAddress);
                $out.write_string (loginName);
                $out.write_string (password);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                unregisterEquipment (macAddress, loginName, password        );
            } finally {
                _releaseReply ($in);
            }
  } // unregisterEquipment


  /**
     * The loginUser() method creates an interface subscriber session
     * for subscribers who log in using static IP addresses.
     *
     * For subscribers who use a different method to log in, use the login()
     * method of the Subscriber interface. 
     *
     * @param[in] userIp	Subscriber's static IP address.
     *
     * @param[in] loginName   Subscriber's login name. 
     * 
     * @param[in] password    Subscriber's password associated with the login name. 
     *
     * @return false
     *
     * @throws LoginException  Raised if a subscriber login to a subscriber
     * session fails.
     * 
     * @throws SAEException    Raised if there is an unspecified error
     * condition within the SAE.
     */
  public boolean loginUser (String userIp, String loginName, String password) throws net.juniper.smgt.sae.sae.LoginException, net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("loginUser", true);
                $out.write_string (userIp);
                $out.write_string (loginName);
                $out.write_string (password);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/LoginException:1.0"))
                    throw net.juniper.smgt.sae.sae.LoginExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return loginUser (userIp, loginName, password        );
            } finally {
                _releaseReply ($in);
            }
  } // loginUser


  /**
     * The getRegisteredLogins() method retrieves from the directory 
     * a list of all the registered logins that use the specified login name.
     *
     * A registered login allows subscribers
     * who use DHCP to have a subscriber session automatically created when their
     * client devices connect to the network using DHCP.  
     *
     * @param[in] login               Subscriber's login name.  
     *      
     * @param[in] password            Subscriber's password associated with the
     * login name. 
     *
     * @return List of objects for registered logins that
     * use the specified login name. 
     *
     * @throws LoginException 	Raised if a subscriber login to a subscriber
     * session fails.
     *
     * @throws SAEException     	Raised if there is an unspecified error
     * condition within the SAE.
     */
  public net.juniper.smgt.sae.sae.Registration[] getRegisteredLogins (String login, String password) throws net.juniper.smgt.sae.sae.LoginException, net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRegisteredLogins", true);
                $out.write_string (login);
                $out.write_string (password);
                $in = _invoke ($out);
                net.juniper.smgt.sae.sae.Registration $result[] = net.juniper.smgt.sae.sae.RegistrationSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/LoginException:1.0"))
                    throw net.juniper.smgt.sae.sae.LoginExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRegisteredLogins (login, password        );
            } finally {
                _releaseReply ($in);
            }
  } // getRegisteredLogins


  /**
     * The getRegisteredEquipment() method retrieves a list of a 
     * subscriber's client devices that use a DHCP connection and are
     * registered to automatically obtain an authenticated IP address. 
     *
     * @param[in] login       Subscriber's login name.  	
     *
     * @param[in] password    Subscriber's password associated
     * with the login name.
     *
     * @return List of registration objects.  
     *
     * @throws LoginException Raised if a subscriber login to a subscriber
     * session fails.
     * 
     * @throws SAEException  Raised if there is an unspecified
     * error condition within the SAE.
     */
  public net.juniper.smgt.sae.sae.Registration[] getRegisteredEquipment (String login, String password) throws net.juniper.smgt.sae.sae.LoginException, net.juniper.smgt.sae.sae.SAEException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRegisteredEquipment", true);
                $out.write_string (login);
                $out.write_string (password);
                $in = _invoke ($out);
                net.juniper.smgt.sae.sae.Registration $result[] = net.juniper.smgt.sae.sae.RegistrationSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:smgt.juniper.net/sae/LoginException:1.0"))
                    throw net.juniper.smgt.sae.sae.LoginExceptionHelper.read ($in);
                else if (_id.equals ("IDL:smgt.juniper.net/sae/SAEException:1.0"))
                    throw net.juniper.smgt.sae.sae.SAEExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRegisteredEquipment (login, password        );
            } finally {
                _releaseReply ($in);
            }
  } // getRegisteredEquipment

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:smgt.juniper.net/sae/SAEAccess:1.0", 
    "IDL:smgt.juniper.net/sae/SAEFeature:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _SAEAccessStub
