package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ArgumentsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saescript.idl
* Sunday, February 1, 2009 10:24:23 PM EST
*/


/// List of script arguments.
public final class ArgumentsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ArgumentsHolder ()
  {
  }

  public ArgumentsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.ArgumentsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.ArgumentsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.ArgumentsHelper.type ();
  }

}
