package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/AttrSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/// List of attributes.
public final class AttrSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.Attr value[] = null;

  public AttrSeqHolder ()
  {
  }

  public AttrSeqHolder (net.juniper.smgt.sae.sae.Attr[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.AttrSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.AttrSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.AttrSeqHelper.type ();
  }

}
