package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/InterfaceName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class InterfaceName implements org.omg.CORBA.portable.IDLEntity
{
  public String intfName = null;

  ///< Name of the managed interface.
  public String vrName = null;

  public InterfaceName ()
  {
  } // ctor

  public InterfaceName (String _intfName, String _vrName)
  {
    intfName = _intfName;
    vrName = _vrName;
  } // ctor

} // class InterfaceName
