package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/InterfaceIndex.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class InterfaceIndex implements org.omg.CORBA.portable.IDLEntity
{
  public int index = (int)0;

  ///< SNMP interface index (ifIndex).
  public String vrName = null;

  public InterfaceIndex ()
  {
  } // ctor

  public InterfaceIndex (int _index, String _vrName)
  {
    index = _index;
    vrName = _vrName;
  } // ctor

} // class InterfaceIndex
