package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/LongLongSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/// 64-bit integer value for list of eventDates.
public final class LongLongSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public long value[] = null;

  public LongLongSeqHolder ()
  {
  }

  public LongLongSeqHolder (long[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.LongLongSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.LongLongSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.LongLongSeqHelper.type ();
  }

}
