package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/MANUAL.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public interface MANUAL
{

  /// Constructor. Manual service activation trigger.
  public static final String value = "MANUAL";
}
