package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/OverloadExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class OverloadExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.OverloadException value = null;

  public OverloadExceptionHolder ()
  {
  }

  public OverloadExceptionHolder (net.juniper.smgt.sae.sae.OverloadException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.OverloadExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.OverloadExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.OverloadExceptionHelper.type ();
  }

}
