package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/SAEAccess.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * Interface to access the SAE core API.
   *
   * Descendant of sae.SAEFeature. 
   * Accessible through the ServiceActivationEngine interface
   * SAEFeature.getFeature.
   */
public interface SAEAccess extends SAEAccessOperations, net.juniper.smgt.sae.sae.SAEFeature, org.omg.CORBA.portable.IDLEntity 
{
} // interface SAEAccess
