package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/SAEFeatureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sae.idl
* Sunday, February 1, 2009 10:24:12 PM EST
*/


/**
   * Common interface for SAE interface modules. Actual interface
   * modules must extend this interface.
   */
public final class SAEFeatureHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.SAEFeature value = null;

  public SAEFeatureHolder ()
  {
  }

  public SAEFeatureHolder (net.juniper.smgt.sae.sae.SAEFeature initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.SAEFeatureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.SAEFeatureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.SAEFeatureHelper.type ();
  }

}
