package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/SAET.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/// Types of exceptions for ServiceAuthenticationException.
public class SAET implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 14;
  private static net.juniper.smgt.sae.sae.SAET[] __array = new net.juniper.smgt.sae.sae.SAET [__size];

  public static final int _SAET_PUBLIC_IP_AUTHENTICATION = 0;
  public static final net.juniper.smgt.sae.sae.SAET SAET_PUBLIC_IP_AUTHENTICATION = new net.juniper.smgt.sae.sae.SAET(_SAET_PUBLIC_IP_AUTHENTICATION);
  public static final int _SAET_MUTEX_GROUPS = 1;
  public static final net.juniper.smgt.sae.sae.SAET SAET_MUTEX_GROUPS = new net.juniper.smgt.sae.sae.SAET(_SAET_MUTEX_GROUPS);
  public static final int _SAET_SERVICE_AUTHORIZATION = 2;
  public static final net.juniper.smgt.sae.sae.SAET SAET_SERVICE_AUTHORIZATION = new net.juniper.smgt.sae.sae.SAET(_SAET_SERVICE_AUTHORIZATION);
  public static final int _SAET_ANONYMOUS_USER = 3;
  public static final net.juniper.smgt.sae.sae.SAET SAET_ANONYMOUS_USER = new net.juniper.smgt.sae.sae.SAET(_SAET_ANONYMOUS_USER);
  public static final int _SAET_AUTH_PRECLUDES_ACTIVATE_ON_LOGIN = 4;
  public static final net.juniper.smgt.sae.sae.SAET SAET_AUTH_PRECLUDES_ACTIVATE_ON_LOGIN = new net.juniper.smgt.sae.sae.SAET(_SAET_AUTH_PRECLUDES_ACTIVATE_ON_LOGIN);
  public static final int _SAET_INHERITED_SUBSCRIPTION = 5;
  public static final net.juniper.smgt.sae.sae.SAET SAET_INHERITED_SUBSCRIPTION = new net.juniper.smgt.sae.sae.SAET(_SAET_INHERITED_SUBSCRIPTION);
  public static final int _SAET_SERVICE_UNAVAILABLE = 6;
  public static final net.juniper.smgt.sae.sae.SAET SAET_SERVICE_UNAVAILABLE = new net.juniper.smgt.sae.sae.SAET(_SAET_SERVICE_UNAVAILABLE);
  public static final int _SAET_SUBSCRIPTION_AUTHORIZATION = 7;
  public static final net.juniper.smgt.sae.sae.SAET SAET_SUBSCRIPTION_AUTHORIZATION = new net.juniper.smgt.sae.sae.SAET(_SAET_SUBSCRIPTION_AUTHORIZATION);
  public static final int _SAET_ACTIVATE_ONLY = 8;
  public static final net.juniper.smgt.sae.sae.SAET SAET_ACTIVATE_ONLY = new net.juniper.smgt.sae.sae.SAET(_SAET_ACTIVATE_ONLY);
  public static final int _SAET_INVISIBLE = 9;
  public static final net.juniper.smgt.sae.sae.SAET SAET_INVISIBLE = new net.juniper.smgt.sae.sae.SAET(_SAET_INVISIBLE);
  public static final int _SAET_FILTERED_OUT = 10;
  public static final net.juniper.smgt.sae.sae.SAET SAET_FILTERED_OUT = new net.juniper.smgt.sae.sae.SAET(_SAET_FILTERED_OUT);
  public static final int _SAET_NO_SESSION_MODIFICATION = 11;
  public static final net.juniper.smgt.sae.sae.SAET SAET_NO_SESSION_MODIFICATION = new net.juniper.smgt.sae.sae.SAET(_SAET_NO_SESSION_MODIFICATION);
  public static final int _SAET_TRANSIENT_EXCEPTION = 12;
  public static final net.juniper.smgt.sae.sae.SAET SAET_TRANSIENT_EXCEPTION = new net.juniper.smgt.sae.sae.SAET(_SAET_TRANSIENT_EXCEPTION);
  public static final int _SAET_PERSISTENT_ACTIVATION = 13;
  public static final net.juniper.smgt.sae.sae.SAET SAET_PERSISTENT_ACTIVATION = new net.juniper.smgt.sae.sae.SAET(_SAET_PERSISTENT_ACTIVATION);

  public int value ()
  {
    return __value;
  }

  public static net.juniper.smgt.sae.sae.SAET from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SAET (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SAET
