package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScheduleEntry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class ScheduleEntry implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  ///<ID of a service schedule entry in the directory.
  public net.juniper.smgt.sae.sae.ScheduledTime schedTime = null;

  ///<Time to schedule a service action.
  public net.juniper.smgt.sae.sae.ActionExt actions[] = null;

  public ScheduleEntry ()
  {
  } // ctor

  public ScheduleEntry (String _id, net.juniper.smgt.sae.sae.ScheduledTime _schedTime, net.juniper.smgt.sae.sae.ActionExt[] _actions)
  {
    id = _id;
    schedTime = _schedTime;
    actions = _actions;
  } // ctor

} // class ScheduleEntry
