package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScheduledTimeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

abstract public class ScheduledTimeHelper
{
  private static String  _id = "IDL:smgt.juniper.net/sae/ScheduledTime:1.0";

  public static void insert (org.omg.CORBA.Any a, net.juniper.smgt.sae.sae.ScheduledTime that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static net.juniper.smgt.sae.sae.ScheduledTime extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = net.juniper.smgt.sae.sae.TimeSpecHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "firstTimeSpec",
            _tcOf_members0,
            null);
          _tcOf_members0 = net.juniper.smgt.sae.sae.TimeSpecHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "secondTimeSpec",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (net.juniper.smgt.sae.sae.ScheduledTimeHelper.id (), "ScheduledTime", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static net.juniper.smgt.sae.sae.ScheduledTime read (org.omg.CORBA.portable.InputStream istream)
  {
    net.juniper.smgt.sae.sae.ScheduledTime value = new net.juniper.smgt.sae.sae.ScheduledTime ();
    value.firstTimeSpec = net.juniper.smgt.sae.sae.TimeSpecHelper.read (istream);
    value.secondTimeSpec = net.juniper.smgt.sae.sae.TimeSpecHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.juniper.smgt.sae.sae.ScheduledTime value)
  {
    net.juniper.smgt.sae.sae.TimeSpecHelper.write (ostream, value.firstTimeSpec);
    net.juniper.smgt.sae.sae.TimeSpecHelper.write (ostream, value.secondTimeSpec);
  }

}
