package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScriptProcessor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saescript.idl
* Sunday, February 1, 2009 10:24:23 PM EST
*/

public interface ScriptProcessor extends ScriptProcessorOperations, net.juniper.smgt.sae.sae.SAEFeature, org.omg.CORBA.portable.IDLEntity 
{
} // interface ScriptProcessor
