package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/ScriptProcessorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saescript.idl
* Sunday, February 1, 2009 10:24:23 PM EST
*/

abstract public class ScriptProcessorHelper
{
  private static String  _id = "IDL:smgt.juniper.net/sae/ScriptProcessor:1.0";

  public static void insert (org.omg.CORBA.Any a, net.juniper.smgt.sae.sae.ScriptProcessor that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static net.juniper.smgt.sae.sae.ScriptProcessor extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (net.juniper.smgt.sae.sae.ScriptProcessorHelper.id (), "ScriptProcessor");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static net.juniper.smgt.sae.sae.ScriptProcessor read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ScriptProcessorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.juniper.smgt.sae.sae.ScriptProcessor value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static net.juniper.smgt.sae.sae.ScriptProcessor narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof net.juniper.smgt.sae.sae.ScriptProcessor)
      return (net.juniper.smgt.sae.sae.ScriptProcessor)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      net.juniper.smgt.sae.sae._ScriptProcessorStub stub = new net.juniper.smgt.sae.sae._ScriptProcessorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static net.juniper.smgt.sae.sae.ScriptProcessor unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof net.juniper.smgt.sae.sae.ScriptProcessor)
      return (net.juniper.smgt.sae.sae.ScriptProcessor)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      net.juniper.smgt.sae.sae._ScriptProcessorStub stub = new net.juniper.smgt.sae.sae._ScriptProcessorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
