package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/SubscriberIterator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/**
   * Interface that is used to iteratively retrieve subscriber objects that were
   * not transmitted from a single API call to the SAE.
   *
   * \b NOTE: If the SubscriberIterator is not used for an allotted time,
   * the garbage collector takes care of it.
   */
public interface SubscriberIterator extends SubscriberIteratorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SubscriberIterator
