package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/SubscriberIdTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/


/// Types of subscriber IDs.
abstract public class SubscriberIdTypeHelper
{
  private static String  _id = "IDL:smgt.juniper.net/sae/SubscriberIdType:1.0";

  public static void insert (org.omg.CORBA.Any a, net.juniper.smgt.sae.sae.SubscriberIdType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static net.juniper.smgt.sae.sae.SubscriberIdType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (net.juniper.smgt.sae.sae.SubscriberIdTypeHelper.id (), "SubscriberIdType", new String[] { "SIT_ADDRESS", "SIT_DN", "SIT_LOGIN_NAME", "SIT_IF_NAME", "SIT_IF_INDEX", "SIT_PRIMARY_USER_NAME", "SIT_ADDR_IF_NAME", "SIT_TUNNEL_SESSION", "SIT_SESSIONID"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static net.juniper.smgt.sae.sae.SubscriberIdType read (org.omg.CORBA.portable.InputStream istream)
  {
    return net.juniper.smgt.sae.sae.SubscriberIdType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.juniper.smgt.sae.sae.SubscriberIdType value)
  {
    ostream.write_long (value.value ());
  }

}
