package net.juniper.smgt.sae.sae;


/**
* net/juniper/smgt/sae/sae/UnknownSubscriptionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class UnknownSubscriptionException extends org.omg.CORBA.UserException
{
  public String subscriptionName = null;
  public String message = null;

  public UnknownSubscriptionException ()
  {
    super(UnknownSubscriptionExceptionHelper.id());
  } // ctor

  public UnknownSubscriptionException (String _subscriptionName, String _message)
  {
    super(UnknownSubscriptionExceptionHelper.id());
    subscriptionName = _subscriptionName;
    message = _message;
  } // ctor


  public UnknownSubscriptionException (String $reason, String _subscriptionName, String _message)
  {
    super(UnknownSubscriptionExceptionHelper.id() + "  " + $reason);
    subscriptionName = _subscriptionName;
    message = _message;
  } // ctor

} // class UnknownSubscriptionException
