package net.juniper.smgt.sae.sae;

/**
* net/juniper/smgt/sae/sae/UnknownSubscriptionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from saeaccess.idl
* Sunday, February 1, 2009 10:24:16 PM EST
*/

public final class UnknownSubscriptionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public net.juniper.smgt.sae.sae.UnknownSubscriptionException value = null;

  public UnknownSubscriptionExceptionHolder ()
  {
  }

  public UnknownSubscriptionExceptionHolder (net.juniper.smgt.sae.sae.UnknownSubscriptionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.juniper.smgt.sae.sae.UnknownSubscriptionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    net.juniper.smgt.sae.sae.UnknownSubscriptionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.juniper.smgt.sae.sae.UnknownSubscriptionExceptionHelper.type ();
  }

}
