package wftac.example.wss001c;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon May 28 21:24:48 EDT 2012
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://wss001.example.wftac/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://wss001.example.wftac/", className = "wftac.example.wss001c.Greet")
    @WebMethod
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://wss001.example.wftac/", className = "wftac.example.wss001c.GreetResponse")
    public java.lang.String greet(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
